# Generated by Django 6.0.2 on 2026-03-03 23:29

from django.db import migrations

CATEGORIES = [
    "Rent",
    "Utilities",
    "Groceries",
    "Dining Out",
    "Transportation",
    "Internet & Phone",
    "Household Supplies",
    "Laundry",
    "Entertainment",
    "Travel",
    "Medical",
    "Insurance",
    "Subscriptions",
    "Clothing",
    "Gifts",
    "Other",
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")
    Category.objects.filter(name__in=CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=unseed_categories),
    ]
