# Generated by Django 6.0.2 on 2026-03-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('role_changed', 'Role Changed'), ('percentage_changed', 'Percentage Changed'), ('member_deactivated', 'Member Deactivated'), ('ownership_transferred', 'Ownership Transferred'), ('expense_deleted', 'Expense Deleted')], max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('acted_by', models.ForeignKey(help_text='The member who performed the action.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to='groups.groupmember')),
                ('group_member', models.ForeignKey(help_text='The member whose record was affected.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='groups.groupmember')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
