# Generated by Django 6.0.2 on 2026-03-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('percentage_changed', 'Your contribution percentage changed'), ('member_deactivated', 'A member was deactivated'), ('ownership_transferred', 'Group ownership was transferred')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='groups.groupmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
