# Generated by Django 6.0.2 on 2026-03-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('balance_snapshot', models.DecimalField(decimal_places=2, help_text="The recipient's balance at the time this notification was generated.", max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='groups.group')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications_received', to='groups.groupmember')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null if system-triggered.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_triggered', to='groups.groupmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
